services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Clickstorm\CsSeo\:
    resource: '../Classes/*'

  Clickstorm\CsSeo\Service\Backend\GridService:
    public: true

  Clickstorm\CsSeo\Hook\SqlExpectedSchemaHook:
    tags:
      - name: event.listener
        identifier: 'cs_seo/SqlExpectedSchemaHook'
        after: 'addMysqlFulltextIndex'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
        method: 'addMetadataDatabaseSchemaToTablesDefinition'

  Clickstorm\CsSeo\EventListener\CanonicalListener:
    tags:
      - name: event.listener
        identifier: 'cs-seo/canonical'
        event: TYPO3\CMS\Seo\Event\ModifyUrlForCanonicalTagEvent

  Clickstorm\CsSeo\EventListener\HrefLangListener:
    tags:
      - name: event.listener
        identifier: 'cs_seo/CsSeoHrefLang'
        after: 'typo3-seo/hreflangGenerator'
        event: TYPO3\CMS\Frontend\Event\ModifyHrefLangTagsEvent
